version: "3.8"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 27017:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_MONGODB_PORT=$MONGODB_DOCKER_PORT
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - network
  api:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 9000:$API_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
    networks:
      - network
  # client:
  #   depends_on:
  #     - api
  #   build:
  #     context: ./client
  #     args:
  #       - API_BASE_URL=$API_BASE_URL
  #   ports:
  #     - 3000:$CLIENT_DOCKER_PORT
  #   networks:
  #     - network

volumes:
  db:

networks:
  network:
    driver: bridge